version = 1

exclude_patterns = [
  ".github/**",
  "data/**",
  "docs/**",
  "src/util/vision/ArucoSamplesUtility.hpp",
  "tests/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    ".devcontainer/Jammy.dockerfile",
    ".devcontainer/JetPack.dockerfile",
    "tools/action-runners/Jammy.dockerfile",
    "tools/action-runners/JetPack.dockerfile"
  ]

[[analyzers]]
name = "cxx"
  [analyzers.meta]
  misra_compliance = true
  cyclomatic_complexity_threshold = "very-high"

