version = 1

exclude_patterns = [
  ".github/**",
  "data/**",
  "docs/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    ".devcontainer/Dockerfile_Jammy",
    ".devcontainer/Dockerfile_JetPack",
    "tools/action-runners/Dockerfile_Jammy",
    "tools/action-runners/Dockerfile_JetPack"
  ]

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "yapf"

[[transformers]]
name = "ruff"
