---
version: '3.8'

services:
  jammy-runner:
    image: ghcr.io/missourimrdt/jammy-runner:latest
    build:
      context: .
      dockerfile: Dockerfile_Jammy
      args:
        RUNNER_VERSION: '2.309.0'
    environment:
      GH_TOKEN: <TOKEN HERE>
      GH_OWNER: MissouriMRDT
      GH_REPOSITORY: Autonomy_Software
  jetpack-runner:
    image: ghcr.io/missourimrdt/jetpack-runner:latest
    build:
      context: .
      dockerfile: Dockerfile_JetPack
      args:
        RUNNER_VERSION: '2.309.0'
    environment:
      GH_TOKEN: <TOKEN HERE>
      GH_OWNER: MissouriMRDT
      GH_REPOSITORY: Autonomy_Software
