name: Code Coverage

on:
  pull_request:
    branches: ["development"]

  push:
    branches: ["development"]

  workflow_dispatch:

concurrency:
  group: "coverage"
  cancel-in-progress: false

jobs:
  analyze-code-coverage:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Setup Action Environment
        if: always()
        run: |
          cd /opt
          if [ ! -d "Autonomy_Software" ]; then git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/Autonomy_Software.git; fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory /opt/Autonomy_Software

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Update Branch
        run: |
          cd /opt/Autonomy_Software/
          git fetch --force --recurse-submodules
          branch=${{ steps.extract_branch.outputs.branch }}
          echo ${{ github.event.pull_request.head.sha }}
          git reset --hard ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
          # git pull --ff-only
          git submodule update --force --recursive --init
          git config --global --add safe.directory /opt/Autonomy_Software/external

      - name: Configure and Build
        run: |
          cd /opt/Autonomy_Software/
          if [ -d "build" ]; then rm -Rf build; fi
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTS_MODE=ON -DBUILD_CODE_COVERAGE=ON -DBUILD_VERBOSE_MODE=ON
          make -j8

      - name: Test
        run: |
          cd /opt/Autonomy_Software/build
          ctest --output-on-failure -T Test -T Coverage
          ctest --output-on-failure --output-junit Test.xml
          gcovr --root . --xml-pretty --output Coverage.xml
          lcov -c -d . -o coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          root_dir: /opt/Autonomy_Software
          working-directory: /opt/Autonomy_Software
          verbose: true
          plugin: gcov
          directory: /opt/Autonomy_Software/build
          file: /opt/Autonomy_Software/build/Coverage.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          root_dir: /opt/Autonomy_Software
          working-directory: /opt/Autonomy_Software/build
          verbose: true
          directory: /opt/Autonomy_Software/build/
          file: Test.xml

      - name: Cleanup Action Environment
        if: always()
        run: |
          cd /opt
          rm -rf /opt/Autonomy_Software
