name: Build and Create Autonomy Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  packages: read
  id-token: write

concurrency:
  group: "create-release"
  cancel-in-progress: false

jobs:
  create-release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Version
        id: version
        run: "echo ::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: "Autonomy Software ${{ steps.version.outputs.version }}"
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        container: [
            "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-08",
            # "ghcr.io/missourimrdt/autonomy-jetpack:2023-06-18",
          ]
    container: ${{ matrix.container }}

    steps:
      - name: Configure the project
        uses: threeal/cmake-action@v1.2.0
        with:
          source-dir: /opt/Autonomy_Software/
          build-dir: /opt/Autonomy_Software/build
          run-build: true

      - name: Print Files
        run: |
          echo "Repo Scope:"
          ls /opt/Autonomy_Software
          echo ""
          echo "Build Scope:"
          ls /opt/Autonomy_Software/build

      - name: Test Access to URL
        run: echo ${{ needs.create-release.outputs.upload_url }}
