name: Build and Create Autonomy Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: read
  id-token: write

concurrency:
  group: "create-release"
  cancel-in-progress: false

jobs:
  create-release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@2

      - name: Determine Version
        id: version
        run: "echo ::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Create Draft Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Autonomy Software ${{ steps.version.outputs.version }}"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        container:
          [
            ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-06,
            ghcr.io/missourimrdt/autonomy-jetpack:2023-06-18,
          ]
    container: ${{ matrix.container }}

    steps:
      - name: Build ARM64 Executable
        run: |
          mkdir build-arm64
          cd build-arm64
          cmake -G -DCMAKE_BUILD_TYPE_Debug ..
          cmake --build .
          ls
          cd
          ls

      - name: Test Access to URL
        run: echo ${{ needs.create-release.outputs.upload_url }}
