name: Build and Create Autonomy Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  packages: read
  id-token: write

concurrency:
  group: "create-release"
  cancel-in-progress: false

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [
            "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-08",
            # "ghcr.io/missourimrdt/autonomy-jetpack:2023-06-18",
          ]
    container: ${{ matrix.container }}

    steps:
      - name: Configure the project
        uses: threeal/cmake-action@v1.2.0
        with:
          source-dir: /opt/Autonomy_Software/
          build-dir: /opt/Autonomy_Software/build
          run-build: true

      - name: Rename Executable for AMD64
        if: contains(${{ matrix.container }}, "autonomy-ubuntu")
        run: mv /opt/Autonomy_Software/build/Autonomy_Software /opt/Autonomy_Software/build/Autonomy_Software_AMD64

      - name: Rename Executable for ARM64
        if: contains(${{ matrix.container }}, "autonomy-jetpack")
        run: mv /opt/Autonomy_Software/build/Autonomy_Software /opt/Autonomy_Software/build/Autonomy_Software_ARM64

      - name: Upload Artifact for AMD64
        if: contains(${{ matrix.container }}, "autonomy-ubuntu")
        uses: actions/upload-artifact@v3
        with:
          name: Autonomy-AMD64
          path: /opt/Autonomy_Software/build/Autonomy_Software_AMD64

      - name: Upload Artifact for ARM64
        if: contains(${{ matrix.container }}, "autonomy-jetpack")
        uses: actions/upload-artifact@v3
        with:
          name: Autonomy-ARM64
          path: /opt/Autonomy_Software/build/Autonomy_Software_ARM64

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Version
        id: version
        run: "echo ::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: /opt/Autonomy_Software/build/

      - name: Display Structure
        run: ls
        working-directory: /opt/Autonomy_Software/build/

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: "Autonomy Software ${{ steps.version.outputs.version }}"
          tag: ${{ github.ref }}
          artifacts: "/opt/Autonomy_Software/build/Autonomy_Software_AMD64"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
