name: Build and Publish Ubuntu Dockerfile

on:
  # Runs workflow 'automatically' when a pull request for the development
  # branch is made and documentaion files have been edited.
  pull_request:
    branches: ['development']
    paths: ['.devcontainer/Dockerfile_Ubuntu']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write

concurrency:
  group: "docker-ubuntu"
  cancel-in-progress: false

jobs:
  get_message:
    name: 'Get commit message'
    runs-on: ubuntu-latest
    steps:
      - name: Get commits
        env:
          # github URL to list commits
          COMMITS_URL: ${{ github.event.pull_request.commits_url }}
        run: |
          if [ "${COMMITS_URL}x" != "x" ]; then
            # get commits list and pick up last one by jq
            # caution: only 100 commits will be taken by curl
            # if your PR has more than 100 commits
            # you have to set page query parameter
            # and request last page commits
            # API URL details: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request
            LAST_MSG=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${COMMITS_URL}?per_page=100" | jq -r .[-1].commit.message)
            # set environment variable
            echo "LAST_MSG=${LAST_MSG}" >> "${GITHUB_ENV}"
          else
            echo 'LAST_MSG=' >> "${GITHUB_ENV}"
          fi

      - name: Print Commit Message
        run: echo '${LAST_MSG}'

  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    if: ${{ contains('$LAST_MSG', '** Build and Publish JetPack Image **') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get repository owner/repository and convert to lowercase string
        id: repo-name-string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Ubuntu Image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ".devcontainer/Dockerfile_Ubuntu"
          tags: "ghcr.io/${{ steps.repo-name-string.outputs.lowercase }}:zed4.0-cuda11.4-opencv4.7.0-ubuntu20.04"
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
