name: Build and Publish JetPack Dockerfile

on:
  push:
    paths: ['.devcontainer/Dockerfile_JetPack']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build JetPack Image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ".devcontainer/Dockerfile_JetPack"
          tags: missourimrdt/autonomy_software:zed4.0-cuda11.4-opencv4.7.0-jp5.1.1
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}