name: Build and Publish Ubuntu Dockerfile

on:
  push:
    paths: ['.devcontainer/Dockerfile_Ubuntu']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "docker-ubuntu"
  cancel-in-progress: false

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get repository owner/repository and convert to lowercase string
        id: repo-name-string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

       - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Ubuntu Image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ".devcontainer/Dockerfile_Ubuntu"
          tags: "ghcr.io/${{ steps.repo-name-string.outputs.lowercase }}:zed4.0-cuda11.4-opencv4.7.0-ubuntu20.04"
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}