name: Unit Tests

on:
  pull_request:
    branches: ["development"]
  workflow_dispatch:

concurrency:
  group: "unit-tests"
  cancel-in-progress: false

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, [self-hosted, linux, ARM64]]
        container:
          [
            "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-23-rev2",
            "ghcr.io/missourimrdt/autonomy-jetpack:2023-07-23-rev3",
          ]
        architecture: [AMD64, ARM64]
        exclude:
          - os: ubuntu-latest
            container: "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-23-rev2"
            architecture: ARM64
          - os: ubuntu-latest
            container: "ghcr.io/missourimrdt/autonomy-jetpack:2023-07-23-rev3"
            architecture: ARM64
          - os: ubuntu-latest
            container: "ghcr.io/missourimrdt/autonomy-jetpack:2023-07-23-rev3"
            architecture: ARM64
          - os: ubuntu-latest
            container: "ghcr.io/missourimrdt/autonomy-jetpack:2023-07-23-rev3"
            architecture: AMD64
          - os: [self-hosted, linux, ARM64]
            container: "ghcr.io/missourimrdt/autonomy-jetpack:2023-07-23-rev3"
            architecture: AMD64
          - os: [self-hosted, linux, ARM64]
            container: "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-23-rev2"
            architecture: AMD64
          - os: [self-hosted, linux, ARM64]
            container: "ghcr.io/missourimrdt/autonomy-ubuntu:2023-07-23-rev2"
            architecture: ARM64

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout Tag
        run: |
          cd /opt/Autonomy_Software/
          git fetch --force
          branch=${{ steps.extract_branch.outputs.branch }}
          echo $branch
          git checkout $branch
          git pull

      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: "."
          builddir: "build"
          cmakeoptions: "--config Debug"
          ctestoptions: ""
